import type { Metadata } from "next";
import localFont from "next/font/local";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";

import { ClientProviders } from "@/components/ClientProviders";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";

// Self-hosted faces via `next/font/local`. Switched from `next/font/google`
// in CHUNK 9.5 because `next build` was wedging on Google Fonts upstream
// retries with no fallback. .woff2 files live in `public/fonts/`,
// Latin-subset only (~68KB total). Tailwind utility classes consume them
// via the same three CSS variables the design tokens expect:
//   --font-display / --font-body / --font-mono
//
// DM Sans is a variable font on Google's side — the single downloaded
// .woff2 covers the full weight axis, so the file is re-referenced for
// each weight we declare. Instrument Serif and DM Mono are static
// single-weight faces (no italic on Instrument Serif per DESIGN.md's
// "upright headlines" rule).
const instrumentSerif = localFont({
  src: [
    {
      path: "../../public/fonts/instrument-serif-400.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-instrument-serif",
  display: "swap",
});

const dmSans = localFont({
  src: [
    {
      path: "../../public/fonts/dm-sans-variable.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/dm-sans-variable.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-dm-sans",
  display: "swap",
});

const dmMono = localFont({
  src: [
    {
      path: "../../public/fonts/dm-mono-400.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dm-mono",
  display: "swap",
});

// OG image is auto-generated by app/opengraph-image.tsx via Next 15's
// ImageResponse pipeline — token-derived, no external assets required.
// Both openGraph and twitter cards inherit it implicitly.
export const metadata: Metadata = {
  title: "PACT — Settlement protocol for verifiable AI-as-a-Service on 0G mainnet",
  description:
    "Sellers mint Agent INFTs, buyers pay per inference, TEE-attested " +
    "ECDSA signature recoverable on-chain. Reputation accrues to the INFT.",
  metadataBase: new URL("https://trypact.xyz"),
  openGraph: {
    title: "PACT — Provable Agent-to-Agent Compute Trust",
    description:
      "Every inference produces a TEE-attested ECDSA signature recoverable on-chain. " +
      "Reputation accrues to the INFT.",
    type: "website",
    url: "https://trypact.xyz",
    siteName: "PACT",
  },
  twitter: {
    card: "summary_large_image",
    title: "PACT — Provable Agent-to-Agent Compute Trust",
    description:
      "Settlement protocol for verifiable AI-as-a-Service on 0G mainnet. " +
      "TEE-attested ECDSA + ERC-7857 reputation.",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${instrumentSerif.variable} ${dmSans.variable} ${dmMono.variable}`}
    >
      <body className="min-h-screen flex flex-col">
        <ClientProviders>
          <Nav />
          <main className="flex-1">{children}</main>
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
