// Extracts ABIs from forge build artifacts at packages/contracts/out/<File>.sol/<Name>.json
// and writes them to packages/shared/src/abis.ts as typed `as const` arrays.
//
// Run after each `forge build` if a contract's interface changed:
//   node packages/shared/scripts/extract-abis.mjs
//
// Idempotent. Overwrites src/abis.ts every run.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..", "..");
const OUT_DIR = join(REPO_ROOT, "packages", "contracts", "out");
const TARGET = join(HERE, "..", "src", "abis.ts");

// (file, contract name) — match forge's out layout.
const TARGETS = [
  ["AttestationVerifier.sol", "AttestationVerifier"],
  ["PactRegistry.sol", "PactRegistry"],
  ["PactEscrow.sol", "PactEscrow"],
  ["ReputationVault.sol", "ReputationVault"],
  ["SlashingArbiter.sol", "SlashingArbiter"],
  ["AgentNFT.sol", "AgentNFT"],
];

const lines = [
  "// AUTO-GENERATED by scripts/extract-abis.mjs — do not hand-edit.",
  "// Re-run after forge build if any contract interface changed.",
  "//",
  "// ABI arrays are typed `as const` so viem / wagmi can infer function",
  "// signatures and event topics statically.",
  "",
];

for (const [file, name] of TARGETS) {
  const artifactPath = join(OUT_DIR, file, `${name}.json`);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  } catch (e) {
    console.error(`MISSING: ${artifactPath} — run 'forge build' first.`);
    process.exit(1);
  }
  if (!Array.isArray(artifact.abi)) {
    console.error(`BAD ARTIFACT: ${artifactPath} (no .abi array)`);
    process.exit(1);
  }
  lines.push(
    `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    "",
  );
}

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, lines.join("\n"));
console.log(`wrote ${TARGET} with ${TARGETS.length} ABIs`);
